### ISSUE TITLE
News section at www.ssllabs.com has reset itself to 2014

### ISSUE THREAD

**Issue by markokr** [ssllabs/ssllabs-scan#746] opened 2019-09-14 07:44 UTC
And links do not work.  Something happened?

**Comment by naumanshah03** [comment] 2019-09-15 16:44
To give an update we are in the process of fixing it - https://discussions.qualys.com/thread/20109-problems-with-renegotiation-testing-on-ssl-labs-reports#comment-48649

Duplicate of #745

**Closed by naumanshah03** 2019-09-15 16:44 UTC
Labels: duplicate
