### ISSUE TITLE
Preloaded browser list not up-to-date

### ISSUE THREAD

**Issue by J0WI** [ssllabs/ssllabs-scan#317] opened 2016-02-18 18:58 UTC
The HSTS preload browser list is not up-to-date. Reproduced multiple times with the Tor list.

**Comment by ivanr** [comment] 2016-02-22 16:22
You need to be more specific in your bug report. What exactly did you reproduce?

**Comment by J0WI** [comment] 2016-02-22 23:47
Initial request with Tor Browser Bundle was https (no redirect), with HTTPS-Everywhere disabled and without specifying https.
Correct preload header was surfed and host is included in Firefox' nsSTSPreloadList.inc.

SSL Labs doesn't mark the host as included in Tor's HSTS list on stable and dev.

**Comment by ivanr** [comment] 2016-02-24 08:02
Please provide the hostname and the Tor preload list where I can look it up.

**Comment by J0WI** [comment] 2016-02-24 20:33
https://gitweb.torproject.org/tor-browser.git/tree/security/manager/boot/src/nsSTSPreloadList.inc?h=tor-browser-38.6.1esr-6.0-1

eg:
press-anime-nenkan.com
peterdavehello.org

**Comment by ivanr** [comment] 2016-03-04 23:33
This should be fixed now, but the problem is that Tor doesn't have one "current" list that I can follow.

**Closed by ivanr** 2016-03-04 23:33 UTC

**Comment by J0WI** [comment] 2016-03-06 12:46
You could also use the list from Firefox ESR.

**Comment by ivanr** [comment] 2016-03-07 09:04
I think it's the same problem because Mozilla don't have an ESR branch; they create them from whatever mainline release is current at that time. So I thought for Tor I would also follow Firefox nightly; after all, it will eventually be used in Tor. From an outside perspective, the two lists are the same, only delayed.

**Comment by J0WI** [comment] 2016-10-20 22:19
@ivanr this may help you finding the correct branch: https://github.com/EFForg/https-everywhere/issues/7126#issuecomment-255243528
