### ISSUE TITLE
Score penalty of 10% when using the mandatory TLS_AES_256_GCM_SHA384 cipher

### ISSUE THREAD

**Issue by SebDanielsson** [ssllabs/ssllabs-scan#777] opened 2020-02-11 00:30 UTC
When configuring a TLS 1.3 only web server compliant with the [RFC 8446](https://tools.ietf.org/html/rfc8446#section-9.1) you currently get a score penalty because the TLS_AES_256_GCM_SHA384 cipher is allowed.

This should be changed.

**Comment by ArchangeGabriel** [comment] 2020-02-11 09:36
Duplicate of #636, #684, #668.

**Comment by naumanshah03** [comment] 2020-04-08 18:01
I suppose you mean TLS_AES_128_GCM_SHA256 rather than TLS_AES_256_GCM_SHA384

**Comment by ArchangeGabriel** [comment] 2020-04-08 22:54
@naumanshah03 Oh interesting actually, I might have jumped too fast on this one…

**Comment by naumanshah03** [comment] 2020-04-14 17:55
@ArchangeGabriel It's ok you're doing a good work by referring to similar issues for users.

We have removed the mandatory summary message for TLS_AES_128_GCM_SHA256. The **implementsTLS13MandatoryCS** field in API will continue to remain for some time.

These changes are deployed on dev.ssllabs.com v2.1.4

I hope this would help users.

**Closed** 2020-05-14 10:02 UTC
