### ISSUE TITLE
Servers out of compliance with RFC 8446 reported as in compliance.

### ISSUE THREAD

**Issue by myfirstnameispaul** [ssllabs/ssllabs-scan#668] opened 2018-11-27 05:35 UTC
Servers without the TLS_AES_128_GCM_SHA256 cipher suite are not reported as being out of compliance with RFC8446.

![8446not8446](https://user-images.githubusercontent.com/5705007/49060469-814c2280-f1c2-11e8-93a3-8f65192b1870.png)

> **9.1.  Mandatory-to-Implement Cipher Suites**
> 
>    In the absence of an application profile standard specifying
>    otherwise:
> 
>    A TLS-compliant application MUST implement the TLS_AES_128_GCM_SHA256
>    [GCM] cipher suite and SHOULD implement the TLS_AES_256_GCM_SHA384
>    [GCM] and TLS_CHACHA20_POLY1305_SHA256 [RFC8439] cipher suites (see
>    Appendix B.4).

**Comment by tamthing** [comment] 2019-01-25 12:22
This has now been fixed on version 1.32.15.

**Closed** 2019-01-25 12:36 UTC

**Comment by myfirstnameispaul** [comment] 2019-01-27 00:53
@hotaru2k3 Open a ticket.

**Comment by josephcsible** [comment] 2019-02-01 15:07
Fixing this caused bug #684.

**Comment by myfirstnameispaul** [comment] 2020-01-30 15:34
@tamthing 

This bug seems to be still possible. 

> well.. it is possible to get a perfect scan with TLSv1.3 but you'd need to change your `openssl.cnf` a little.
> see: https://www.ssllabs.com/ssltest/analyze.html?d=gottz.de
> 
> just put this above the first section in your `/etc/ssl/openssl.cnf`:
> ```
> openssl_conf = default_conf
> 
> [default_conf]
> ssl_conf = ssl_sect
> 
> [ssl_sect]
> system_default = system_default_sect
> 
> [system_default_sect]
> CipherString = DEFAULT@SECLEVEL=2
> Ciphersuites = TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384
> ```
> this requires a nginx restart. not just a reload.
> 
> oh and just a reminder:
> it's usually bad advice to tamper with openssl.cnf unless you really disagree with the spec


https://github.com/ssllabs/ssllabs-scan/issues/684#issuecomment-580240000

**Comment by ArchangeGabriel** [comment] 2020-02-11 09:33
It does stat ` This server does not support the mandatory cipher suite TLS_AES_128_GCM_SHA256 for TLS 1.3. See RFC 8446 for details. ` though. The issue is the other message.
