### ISSUE TITLE
F Grade because of TLS 1.0 only, but browser says TLS 1.2

### ISSUE THREAD

**Issue by shibumi** [ssllabs/ssllabs-scan#729] opened 2019-07-03 10:44 UTC
Hi,
I have a really weird issue. I have scanned the webserver `https://tu-clausthal.de` via sslabs
and I get the following result:

https://www.ssllabs.com/ssltest/analyze.html?d=tu%2dclausthal.de&s=2001%3a638%3a605%3a20%3a1%3a0%3a0%3a9&latest

![https://paste.xinu.at/cP8h/](https://paste.xinu.at/cP8h/)

But when i visit the page in my browser.. everything is fine with TLS 1.2 and HSTS etc:

![https://paste.xinu.at/tiS1R/](https://paste.xinu.at/tiS1R/)

Any idea?

**Comment by tamthing** [comment] 2019-07-05 05:25
Hi @shibumi , I tried scanning the domain but SSLLabs isn't able to connect to your server. I was thinking of investigating. Did you do something to not enable the connection?

**Comment by shibumi** [comment] 2019-07-05 07:35
Hi @tamthing, try again. It should work now.

**Comment by shibumi** [comment] 2019-07-05 07:42
Btw https://hstspreload.org doesn't seem to connect as well.
https://tls.imirhil.fr/https/tu-clausthal.de works fine... this is pretty weird..

https://observatory.mozilla.org/analyze/tu-clausthal.de#tls gives more details

**Comment by tamthing** [comment] 2019-07-10 05:58
I see that this issue is not observed any more. It shows support for TLS1.3 & TLS1.2 and results in A grade. Did you identify the discrepancy and the cause of it? Please reopen the ticket if you notice the issue again. I'll be closing it.

**Closed by tamthing** 2019-07-10 05:58 UTC

**Comment by shibumi** [comment] 2019-07-10 16:02
@tamthing well, I have no idea. We have nothing changed on our side. But our Firewall vendor is currently investigating an issue in the TLS inspection gateway.. I guess it has something to do with it.
