### ISSUE TITLE
Link for  secure renegotiation is broken

### ISSUE THREAD

**Issue by Fred010101** [ssllabs/ssllabs-scan#738] opened 2019-08-12 14:33 UTC
I scanned a web server that doesn't support secure renegotiation.   The Qualys page displays this message:

There is no support for secure renegotiation. Grade reduced to A-.  MORE INFO »

More Info is a hyperlink to this page:
https://community.qualys.com/blogs/securitylabs/2010/10/06/disabling-ssl-renegotiation-is-a-crutch-not-a-fix?

However that page doesn't exist (the link is broken)

**Comment by tamthing** [comment] 2019-08-13 09:56
Thank you for reporting, we would look into it.

**Comment by FranklinYu** [comment] 2019-08-15 14:35
Yes I noticed that; correct URL is

https://blog.qualys.com/ssllabs/2010/10/06/disabling-ssl-renegotiation-is-a-crutch-not-a-fix-2

**Comment by naumanshah03** [comment] 2019-09-15 16:46
To give an update we are in the process of fixing it - https://discussions.qualys.com/thread/20109-problems-with-renegotiation-testing-on-ssl-labs-reports#comment-48649

For now please use the link mentioned by @FranklinYu 

Duplicate of #745

**Closed by naumanshah03** 2019-09-15 16:46 UTC
Labels: duplicate
