### ISSUE TITLE
Test Your Server appears to have problems

### ISSUE THREAD

**Issue by github-rralston** [ssllabs/ssllabs-scan#64] opened 2015-02-26 12:22 UTC
Known sites are not being reported on or just not responding, but same sites are reported on via the dev site: https://dev.ssllabs.com

**Comment by ivanr** [comment] 2015-02-26 12:33
If I understand your report correctly, when you try enter some names on www.ssllabs.com they don't work, but they do work on dev.ssllabs.com? That's probably because some site owners are blocking the main SSL Labs IP address, but not that of dev.ssllabs.com (which is hosted in a different location).

What are the error messages?

**Comment by github-rralston** [comment] 2015-02-26 12:44
What I was experiencing, even on sites I control, were, for example, “page not found” after submitting a site and waiting a long time, or the site would just churn forever. When I tested at dev site, I got typical results.

This started yesterday for me, but when it persisted this morning I thought I should report it. As I am trying things again now to respond to you, things seem to be “normal” again. So, if it happens again, I will respond again to this thread, perhaps with screen captures.

Thanks Ivan. I really appreciate the site and service it provides, along with documents and book written. Very helpful.

Rob Ralston

**Comment by ivanr** [comment] 2015-02-26 12:47
Ah, I see. That sounds like a network connectivity issue between you and main SSL Labs servers. There was no work done on the productions servers recently so you should not be experiencing any problems (assuming everything works as intended). I'll close this ticket for now but please let me know if you experience problems again. A screenshot would be useful. Thanks.

**Closed by ivanr** 2015-02-26 12:47 UTC
