### ISSUE TITLE
Internal error, TLSv1.3 only site

### ISSUE THREAD

**Issue by nieldk** [ssllabs/ssllabs-scan#804] opened 2020-05-16 14:30 UTC
The scan engine fails with an “internal error” when scanning a TLSv1.3 only site (RSA cert).

For reference: https://www.ssllabs.com/ssltest/analyze.html?d=sec1.dk

**Comment by nayankakati** [comment] 2020-05-18 04:51
Hi @nieldk :

This has already been fixed, please check the same on dev.ssllabs.com, we will deploy to production soon.

Thanks

**Comment by naumanshah03** [comment] 2020-05-18 05:17
Hi @nieldk 

This issue has been fixed and changes have been deployed to dev.ssllabs.com version 2.1.5
Duplicate: https://github.com/ssllabs/ssllabs-scan/issues/795

https://dev.ssllabs.com/ssltest/analyze.html?d=sec1.dk

Regards,
Nauman Shah

**Comment by nieldk** [comment] 2020-05-18 05:29
I can confirm.
However, its not a duplicate, #795 didnt experience this with RSA cert, i
did.

Best regards
Niel

**Comment by naumanshah03** [comment] 2020-06-24 19:50
Hi @nieldk 

It is a duplicate of #795 because the issue was not related to the certificate being used whereas it was related to the use of ChaCha preference in TLS 1.3
Hence I mentioned about #795 issue

As verified able to scan sec1.dk on dev.ssllabs.com

Regards,
Nauman Shah

**Closed** 2020-06-26 09:00 UTC
