### ISSUE TITLE
Update TLS 1.3 scan from draft 28 to RFC8446, please

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#641] opened 2018-08-13 15:25 UTC
https://tools.ietf.org/html/rfc8446

**Comment by ArchangeGabriel** [comment] 2018-08-25 11:37
Dupe of #547.

**Comment by naumanshah03** [comment] 2018-09-24 13:54
Hi @RobTho,

Please find the latest release of SSL Labs verison 1.32.6 on [dev.ssllabs.com](dev.ssllabs.com) which supports TLS 1.3 RFC 8446
![image](https://user-images.githubusercontent.com/22236992/45956101-56f9af80-c02f-11e8-9621-b1ed473bd660.png)

**Closed** 2019-03-11 10:15 UTC
